//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Informationssegmente
    {
        public int Informationssegment_Id { get; set; }
        public string Name { get; set; }
        public string Segment { get; set; }
        public string Beschreibung { get; set; }
        public string Mögliche_Segmentinhalte { get; set; }
        public string Attribut_1 { get; set; }
        public string Attribut_2 { get; set; }
        public string Attribut_3 { get; set; }
        public string Attribut_4 { get; set; }
        public string Attribut_5 { get; set; }
        public string Attribut_6 { get; set; }
        public string Attribut_7 { get; set; }
        public string Attribut_8 { get; set; }
        public string Attribut_9 { get; set; }
        public string Attribut_10 { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    }
}
