//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Prozesse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISB_BIA_Prozesse()
        {
            this.ISB_BIA_Delta_Analyse = new HashSet<ISB_BIA_Delta_Analyse>();
            this.ISB_BIA_Prozesse_Applikationen = new HashSet<ISB_BIA_Prozesse_Applikationen>();
        }
    
        public int Prozess_Id { get; set; }
        public string OE_Filter { get; set; }
        public string Prozess { get; set; }
        public string Sub_Prozess { get; set; }
        public string Prozessverantwortlicher { get; set; }
        public string Kritischer_Prozess { get; set; }
        public string Kritikalität_des_Prozesses { get; set; }
        public string Reifegrad_des_Prozesses { get; set; }
        public string Regulatorisch { get; set; }
        public string Reputatorisch { get; set; }
        public string Finanziell { get; set; }
        public int SZ_1 { get; set; }
        public int SZ_2 { get; set; }
        public int SZ_3 { get; set; }
        public int SZ_4 { get; set; }
        public int SZ_5 { get; set; }
        public int SZ_6 { get; set; }
        public string Vorgelagerte_Prozesse { get; set; }
        public string Nachgelagerte_Prozesse { get; set; }
        public string Servicezeit_Helpdesk { get; set; }
        public int RPO_Datenverlustzeit_Recovery_Point_Objective { get; set; }
        public int RTO_Wiederanlaufzeit_Recovery_Time_Objective { get; set; }
        public int RTO_Wiederanlaufzeit_Recovery_Time_Objective_Notfall { get; set; }
        public string Relevantes_IS_1 { get; set; }
        public string Relevantes_IS_2 { get; set; }
        public string Relevantes_IS_3 { get; set; }
        public string Relevantes_IS_4 { get; set; }
        public string Relevantes_IS_5 { get; set; }
        public int Aktiv { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISB_BIA_Delta_Analyse> ISB_BIA_Delta_Analyse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISB_BIA_Prozesse_Applikationen> ISB_BIA_Prozesse_Applikationen { get; set; }
    }
}
