//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Settings
    {
        public int Id { get; set; }
        public string SZ_1_Name { get; set; }
        public string SZ_2_Name { get; set; }
        public string SZ_3_Name { get; set; }
        public string SZ_4_Name { get; set; }
        public string SZ_5_Name { get; set; }
        public string SZ_6_Name { get; set; }
        public string Neue_Schutzziele_aktiviert { get; set; }
        public string BIA_abgeschlossen { get; set; }
        public string SBA_abgeschlossen { get; set; }
        public string Delta_abgeschlossen { get; set; }
        public string Attribut9_aktiviert { get; set; }
        public string Attribut10_aktiviert { get; set; }
        public string Multi_Save { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    }
}
