//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Informationssegmente_Attribute
    {
        public int Attribut_Id { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public int SZ_1 { get; set; }
        public int SZ_2 { get; set; }
        public int SZ_3 { get; set; }
        public int SZ_4 { get; set; }
        public int SZ_5 { get; set; }
        public int SZ_6 { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    }
}
