//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Applikationen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISB_BIA_Applikationen()
        {
            this.ISB_BIA_Delta_Analyse = new HashSet<ISB_BIA_Delta_Analyse>();
            this.ISB_BIA_Prozesse_Applikationen = new HashSet<ISB_BIA_Prozesse_Applikationen>();
        }
    
        public int Applikation_Id { get; set; }
        public string Rechenzentrum { get; set; }
        public string Server { get; set; }
        public string Virtuelle_Maschine { get; set; }
        public string Typ { get; set; }
        public string IT_Betriebsart { get; set; }
        public string IT_Anwendung_System { get; set; }
        public string Wichtiges_Anwendungssystem { get; set; }
        public int SZ_1 { get; set; }
        public int SZ_2 { get; set; }
        public int SZ_3 { get; set; }
        public int SZ_4 { get; set; }
        public int SZ_5 { get; set; }
        public int SZ_6 { get; set; }
        public int Aktiv { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISB_BIA_Delta_Analyse> ISB_BIA_Delta_Analyse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISB_BIA_Prozesse_Applikationen> ISB_BIA_Prozesse_Applikationen { get; set; }
    }
}
