//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Prozesse_Applikationen
    {
        public int Prozess_Id { get; set; }
        public System.DateTime Datum_Prozess { get; set; }
        public int Applikation_Id { get; set; }
        public System.DateTime Datum_Applikation { get; set; }
        public int Relation { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    
        public virtual ISB_BIA_Applikationen ISB_BIA_Applikationen { get; set; }
        public virtual ISB_BIA_Prozesse ISB_BIA_Prozesse { get; set; }
    }
}
