//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISB_BIA_Log
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public string Tabelle { get; set; }
        public string Details { get; set; }
        public int Id_1 { get; set; }
        public int Id_2 { get; set; }
        public System.DateTime Datum { get; set; }
        public string Benutzer { get; set; }
    }
}
