//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISB_BIA_IMPORT1.LinqEntityContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }

        public DataEntities(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ISB_BIA_Applikationen> ISB_BIA_Applikationen { get; set; }
        public virtual DbSet<ISB_BIA_Delta_Analyse> ISB_BIA_Delta_Analyse { get; set; }
        public virtual DbSet<ISB_BIA_Informationssegmente> ISB_BIA_Informationssegmente { get; set; }
        public virtual DbSet<ISB_BIA_Informationssegmente_Attribute> ISB_BIA_Informationssegmente_Attribute { get; set; }
        public virtual DbSet<ISB_BIA_Lock> ISB_BIA_Lock { get; set; }
        public virtual DbSet<ISB_BIA_Log> ISB_BIA_Log { get; set; }
        public virtual DbSet<ISB_BIA_OEs> ISB_BIA_OEs { get; set; }
        public virtual DbSet<ISB_BIA_Prozesse> ISB_BIA_Prozesse { get; set; }
        public virtual DbSet<ISB_BIA_Prozesse_Applikationen> ISB_BIA_Prozesse_Applikationen { get; set; }
        public virtual DbSet<ISB_BIA_Settings> ISB_BIA_Settings { get; set; }
    }
}
