<?xml version="1.0" encoding="utf-8"?><Database Name="Data" Class="MyLinqContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Captain\Documents\Data.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ISB_BIA_IMPORT1.Properties.Settings" SettingsPropertyName="DataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ISB_BIA_Applikationen" Member="ISB_BIA_Applikationen">
    <Type Name="ISB_BIA_Applikationen">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Applikation_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rechenzentrum" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Server" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Virtuelle_Maschine" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Typ" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="IT_Betriebsart" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="IT_Anwendung_System" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Wichtiges_Anwendungssystem" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Aktiv" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ISB_BIA_Applikationen_ISB_BIA_Delta_Analyse" Member="ISB_BIA_Delta_Analyse" ThisKey="Applikation_Id,Datum" OtherKey="Applikation_Id,Datum_Applikation" Type="ISB_BIA_Delta_Analyse" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Settings" Member="ISB_BIA_Settings">
    <Type Name="ISB_BIA_Settings">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SZ_1_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_2_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_3_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_4_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_5_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_6_Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Neue_Schutzziele_aktiviert" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BIA_abgeschlossen" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SBA_abgeschlossen" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Delta_abgeschlossen" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut9_aktiviert" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut10_aktiviert" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Multi_Save" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Delta_Analyse" Member="ISB_BIA_Delta_Analyse">
    <Type Name="ISB_BIA_Delta_Analyse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Prozess_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Prozess" Type="System.String" DbType="VarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Sub_Prozess" Type="System.String" DbType="VarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Datum_Prozess" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Applikation_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Applikation" Type="System.String" DbType="VarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Datum_Applikation" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SZ_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ISB_BIA_Applikationen_ISB_BIA_Delta_Analyse" Member="ISB_BIA_Applikationen" ThisKey="Applikation_Id,Datum_Applikation" OtherKey="Applikation_Id,Datum" Type="ISB_BIA_Applikationen" IsForeignKey="true" />
      <Association Name="ISB_BIA_Prozesse_ISB_BIA_Delta_Analyse" Member="ISB_BIA_Prozesse" ThisKey="Prozess_Id,Datum_Prozess" OtherKey="Prozess_Id,Datum" Type="ISB_BIA_Prozesse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Informationssegmente" Member="ISB_BIA_Informationssegmente">
    <Type Name="ISB_BIA_Informationssegmente">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Informationssegment_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Segment" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Beschreibung" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Mögliche_Segmentinhalte" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_1" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_2" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_3" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_4" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_5" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_6" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_7" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_8" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_9" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Attribut_10" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Informationssegmente_Attribute" Member="ISB_BIA_Informationssegmente_Attribute">
    <Type Name="ISB_BIA_Informationssegmente_Attribute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Attribut_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Lock" Member="ISB_BIA_Lock">
    <Type Name="ISB_BIA_Lock">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Table_Flag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Object_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BenutzerNnVn" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Log" Member="ISB_BIA_Log">
    <Type Name="ISB_BIA_Log">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Action" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Tabelle" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Id_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_OEs" Member="ISB_BIA_OEs">
    <Type Name="ISB_BIA_OEs">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OE_Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="OE_Nummer" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Prozesse" Member="ISB_BIA_Prozesse">
    <Type Name="ISB_BIA_Prozesse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Prozess_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OE_Filter" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Prozess" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Sub_Prozess" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Prozessverantwortlicher" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Kritischer_Prozess" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Kritikalität_des_Prozesses" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reifegrad_des_Prozesses" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Regulatorisch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reputatorisch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Finanziell" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SZ_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_4" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_5" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SZ_6" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Vorgelagerte_Prozesse" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Nachgelagerte_Prozesse" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="Servicezeit_Helpdesk" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="RPO_Datenverlustzeit_Recovery_Point_Objective" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RTO_Wiederanlaufzeit_Recovery_Time_Objective" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RTO_Wiederanlaufzeit_Recovery_Time_Objective_Notfall" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Relevantes_IS_1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Relevantes_IS_2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Relevantes_IS_3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Relevantes_IS_4" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Relevantes_IS_5" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Aktiv" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ISB_BIA_Prozesse_ISB_BIA_Delta_Analyse" Member="ISB_BIA_Delta_Analyse" ThisKey="Prozess_Id,Datum" OtherKey="Prozess_Id,Datum_Prozess" Type="ISB_BIA_Delta_Analyse" />
    </Type>
  </Table>
  <Table Name="dbo.ISB_BIA_Prozesse_Applikationen" Member="ISB_BIA_Prozesse_Applikationen">
    <Type Name="ISB_BIA_Prozesse_Applikationen">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Prozess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Applikation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Relation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Benutzer" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>